### ISSUE TITLE
quick question on figure 1B

### ISSUE THREAD

**Issue by kinnaryshah** [lmweber/nnSVG-analyses#1]
Hi @lmweber, hope you are doing well!

I have a quick question about figure 1B ([code](https://github.com/lmweber/nnSVG-analyses/blob/c3a234568a80d200171228d6272541b34a577389/analyses/03_evaluations/evaluations_humanDLPFC_withFiltering.R#L659)). Is the bandwidth parameter scaled in any way or is the x-axis just cut off at 1? Thanks!

**Comment by lmweber** [comment]
Hi @kinnaryshah !

I believe the x-axis is simply cut off at 1, and the values are already scaled internally in nnSVG to be on the same scale as the dimensions of the tissue area (see https://github.com/lmweber/nnSVG/blob/devel/R/nnSVG.R#L242-L244). In this case there may be some larger values not shown on the plot, which may be harder to interpret. Does this make sense? Apologies if I am mis-remembering.

**Comment by kinnaryshah** [comment]
Thank you!

**Comment by kinnaryshah** [comment]
Sorry for re-opening this issue!

I was wondering why the coordinates are scaled to be between 0-1 before using BRISC. Apologies if this justification has already been written!

**Comment by lmweber** [comment]
Hey, apologies for the delay! If I remember correctly, this was for two reasons: (i) scaling the coordinates to the range 0-1 means the units of the length scale parameter estimates can be interpreted in the same way, i.e. estimated length scale of 0.1 is interpreted as 10% of the max width or height of the tissue area (instead of the units being in terms of pixels, which would be the case without scaling) for this parameter in the exponential covariance equation, and (ii) computational stability (I believe I remember there were some computational issues when the coordinates had very large values in terms of pixels).

Let me know if this helps!

**Comment by kinnaryshah** [comment]
Thanks so much!
